const data = {
  "eventsLimit": 5,
  "includeFollowers": "yes",
  "includeRedemptions": "yes",
  "includeHosts": "yes",
  "minHost": 1,
  "includeRaids": "yes",
  "minRaid": 1,
  "includeSubs": "yes",
  "includeTips": "yes",
  "minTip": 1,
  "includeCheers": "yes",
  "minCheer": 1,
  "direction": "top",
  "textOrder": "nameFirst",
  "fadeoutTime": 999,
  "fontColor": "rgb(255, 254, 254)",
  "theme": "texture",
  "backgroundOpacity": 50,
  "backgroundColor": "rgb(114, 0, 255)",
  "iconColor": "rgb(255, 255, 255, 255)",
  "locale": "en-US",
  "messagesLimit": 10,
  "hideAfter": 999,
  "font_size": 22,
  "fontFamily": "Roboto",
  "textAlign": "left",
  "displayType": "inline-block",
  "dividerColor": "#0077FF",
  "enableCustomName": "normalNames",
  "nameColor": "#FFFFFF",
  "separator": ":",
  "fromWeight": "700",
  "bgColor": "rgba(0, 0, 0, 0.2)",
  "bgOpacity": 17,
  "spacing": 0,
  "msgDirection": "fromRight",
  "messageWeight": "400",
  "topPadding": 20,
  "botPadding": 20,
  "hideCommands": "yes",
  "ignoredUsers": "StreamElements,OtherBot",
  "animationOut": "fadeOut",
  "layout": "inline-block",
  "testMessage": "Test message",
  "fontName": "Noto Sans",
  "fontSize": 24,
  "fontWeight": "400",
  "textShadow": "rgb(0, 0, 0) 1px 1px 1px",
  "emoteSize": 32,
  "alignMessages": "flex",
  "nickColor": "user",
  "customNickColor": "rgb(0, 255, 0)",
  "animationIn": "slideInRight",
  "messageAlign": "right",
  "messageOrigin": "bottom",
  "customFont": "{fontName}",
  "noname": "hide",
  "showAvatar": "true",
  "highlightColor": "#A400FF"
}
